spring:
  datasource:
    url: jdbc:mysql://3.34.147.46:3306/choose_one?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: sdan
    password: roqkf!1209
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  messages:
    basename: validation
    encoding: UTF-8

server:
  port: 8080
  address: 0.0.0.0


token:
  secret:
    key: "GuswlstmZLwmsmsRpthrwkftodRutr3945kgjwoALtjijn4@)05842kj"
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 24