name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Create test application.yml
        run: |
          mkdir -p src/test/resources
          echo "spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

  token:
    secret:
      key: '${{ secrets.TEST_TOKEN_KEY }}'
    access-token:
      plus-hour: 1
    refresh-token:
      plus-hour: 24" > src/test/resources/application.yml

      - name: Build and test
        run: ./gradlew build -Dspring.profiles.active=test